import type { Tabs } from './types';
import {
  BriefcaseBusiness,
  CigaretteOff,
  GlassWater,
  Heart,
  HeartHandshake,
  IndianRupee,
  Ruler,
  Sparkles,
  UsersRound,
} from 'lucide-react';

import { user1, user2, user3, user4, user5, user6 } from '@/assets/images';

export const tabs: Tabs[] = [
  {
    id: 'recommended',
    label: 'Recommended',
    count: 0,
  },
  {
    id: 'newMatches',
    label: 'New Matches',
    count: 35,
  },
  {
    id: 'shortlisted',
    label: 'Shortlisted',
    count: 10,
  },
  {
    id: 'interested',
    label: 'Interested',
    count: 15,
  },
  {
    id: 'viewed',
    label: 'Viewed',
    count: 0,
  },
];

export const ageOptions = [
  '18 - 24',
  '25 - 30',
  '31 - 35',
  '36 - 40',
  '41 - 50',
  '51 - 55',
  '55 - 60',
];

export const locationOptions = [
  'Mumbai',
  'Pune',
  'Nagpur',
  'Nashik',
  'Thane',
  'Navi Mumbai',
  'Chhatrapati Sambhajinagar',
  'Kalyan-Dombivli',
  'Vasai-Virar',
  'Mira-Bhayandar',
  'Bhiwandi',
  'Panvel',
  'Solapur',
  'Kolhapur',
  'Amravati',
  'Sangli',
  'Satara',
  'Jalgaon',
  'Akola',
  'Latur',
  'Nanded',
  'Dhule',
  'Ahmednagar',
  'Chandrapur',
  'Parbhani',
  'Beed',
  'Ratnagiri',
  'Wardha',
  'Yavatmal',
  'Buldhana',
  'Jalna',
  'Gondia',
  'Bhandara',
  'Washim',
  'Osmanabad',
  'Hingoli',
  'Sindhudurg',
  'Palghar',
];

export const religionOptions = [
  'Hindu',
  'Muslim',
  'Buddhist',
  'Christian',
  'Jain',
  'Sikh',
  'Parsi',
  'Jewish',
  'Other',
  'Prefer not to say',
];

export const communityOptions = [
  'Brahmin',
  'Rajput',
  'Maratha',
  'Jat',
  'Gujjar',
  'Yadav',
  'Patel',
  'Bania',
  'Kayastha',
  'Kshatriya',
  'Vaishya',
  'Lingayat',
  'Vokkaliga',
  'Reddy',
  'Kamma',
  'Nair',
  'Ezhava',
  'Chettiar',
  'Other',
];

export const communitiesByReligion = {
  Hindu: [
    'Maratha',
    'Brahmin',
    'CKP',
    'Bhandari',
    'Mali',
    'Dhangar',
    'Kunbi',
    'Teli',
    'Gurav',
    'Sutar',
    'Lohar',
    'Kumbhar',
    'Sonar',
    'Shimpi',
    'Koli',
    'Agri',
    'Banjara',
    'Rajput',
    'Lingayat',
    'Vani',
    'Brahma Kshatriya',
    'Other',
  ],

  Muslim: [
    'Sunni',
    'Shia',
    'Sunni Hanafi',
    'Sunni Barelvi',
    'Sunni Deobandi',
    'Bohra',
    'Khoja',
    'Memon',
    'Other',
  ],

  Buddhist: ['Navayana Buddhist', 'Other'],

  Christian: [
    'Catholic',
    'Protestant',
    'Syrian Christian',
    'Maharashtrian Christian',
    'Other',
  ],

  Jain: ['Digambar', 'Shwetambar', 'Sthanakvasi', 'Terapanthi', 'Other'],

  Sikh: ['Jat Sikh', 'Khatri', 'Arora', 'Ramgarhia', 'Other'],

  Parsi: ['Parsi'],

  Jewish: ['Bene Israel', 'Other'],

  Other: ['Other'],

  'Prefer not to say': ['Prefer not to say'],
};

export const educationOptions = [
  '10th',
  '12th',
  'Diploma',
  'ITI',
  'BA',
  'BSc',
  'BCom',
  'BBA',
  'BCA',
  'BE',
  'BTech',
  'MBBS',
  'BDS',
  'LLB',
  'BPharm',
  'BEd',
  'BArch',
  'BFA',
  'MA',
  'MSc',
  'MCom',
  'MBA',
  'MCA',
  'ME',
  'MTech',
  'MD',
  'MS',
  'LLM',
  'MPharm',
  'MEd',
  'MArch',
  'PhD',
  'Other',
];

export const moreFilterOptions = [
  {
    key: 'height',
    title: 'Height',
    icon: Ruler,
    options: [`5'0" - 5'5"`, `5'6" - 6'0"`, `6'1" - 6'6"`, `6'7" - 7'0"`],
  },
  {
    key: 'occupation',
    title: 'Occupation',
    icon: BriefcaseBusiness,
    options: [
      'Software Engineer',
      'Doctor',
      'Teacher',
      'Business Owner',
      'Government Employee',
      'Lawyer',
    ],
  },
  {
    key: 'marital-status',
    title: 'Marital Status',
    icon: HeartHandshake,
    options: ['Never Married', 'Divorced', 'Widowed', 'Separated'],
  },
  {
    key: 'family-type',
    title: 'Family Type',
    icon: UsersRound,
    options: ['Joint Family', 'Nuclear Family', 'Extended Family'],
  },
  {
    key: 'drinking',
    title: 'Drinking',
    icon: GlassWater,
    options: ['Never', 'Occasionally', 'Regularly'],
  },
  {
    key: 'hobbies',
    title: 'Hobbies',
    icon: Heart,
    options: [
      'Reading',
      'Traveling',
      'Music',
      'Photography',
      'Cooking',
      'Sports',
      'Dancing',
      'Gardening',
      'Painting',
      'Drawing',
      'Writing',
      'Singing',
      'Hiking',
      'Cycling',
      'Swimming',
      'Yoga',
      'Fitness',
      'Gaming',
      'Watching Movies',
      'Watching TV Shows',
      'Playing Guitar',
      'Playing Piano',
      'Learning Languages',
      'Blogging',
      'Volunteering',
      'Meditation',
      'Bird Watching',
      'Fishing',
      'Camping',
      'Running',
      'Badminton',
      'Cricket',
      'Football',
      'Chess',
      'Board Games',
      'Crafting',
      'Pottery',
      'Baking',
      'Home Decoration',
      'Collecting',
    ],
  },
  {
    key: 'annual-income',
    title: 'Annual Income',
    icon: IndianRupee,
    options: [
      'Below ₹5 Lakh',
      '₹5 - ₹10 Lakh',
      '₹10 - ₹20 Lakh',
      '₹20 - ₹30 Lakh',
      '₹30 - ₹50 Lakh',
      'Above ₹50 Lakh',
    ],
  },
  {
    key: 'lifestyle',
    title: 'Lifestyle',
    icon: Sparkles,
    options: ['Traditional', 'Moderate', 'Liberal'],
  },
  {
    key: 'smoking',
    title: 'Smoking',
    icon: CigaretteOff,
    options: ['Never', 'Occasionally', 'Regularly'],
  },
];

export const users = [
  {
    id: 1,
    name: 'Priya Patil',
    image: user1,
    about:
      'Warm and family-oriented professional who enjoys traveling, photography, and spending quality time with family.',
    age: 27,
    location: 'Pune, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'MBA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Music', 'Gardening'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 2,
    name: 'Sneha Deshmukh',
    image: user2,
    about:
      'Creative professional who enjoys painting, dancing, photography, and discovering new cuisines.',
    age: 26,
    location: 'Nashik, Maharashtra',
    religion: 'Hindu',
    community: 'Kunbi',
    education: 'BFA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Painting', 'Dancing', 'Cooking'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 3,
    name: 'Neha Joshi',
    image: user3,
    about:
      'Simple and cheerful software professional who enjoys reading, music, yoga, and spending time outdoors.',
    age: 30,
    location: 'Navi Mumbai, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'MCA',
    height: `5'0" - 5'5"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Reading', 'Music', 'Yoga'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 4,
    name: 'Ayesha Shaikh',
    image: user4,
    about:
      'Friendly and ambitious professional who enjoys cooking, writing, traveling, and learning new things.',
    age: 28,
    location: 'Pune, Maharashtra',
    religion: 'Muslim',
    community: 'Bohra',
    education: 'BCom',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Writing', 'Traveling'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 5,
    name: 'Kavita Jadhav',
    image: user5,
    about:
      'Positive and caring person who enjoys gardening, cooking, music, and family gatherings.',
    age: 34,
    location: 'Kolhapur, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'MA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Gardening', 'Cooking', 'Music'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 6,
    name: 'Meera Nair',
    image: user6,
    about:
      'Doctor who enjoys yoga, meditation, traveling, and exploring different cultures.',
    age: 30,
    location: 'Mumbai, Maharashtra',
    religion: 'Hindu',
    community: 'Nair',
    education: 'MBBS',
    height: `5'0" - 5'5"`,
    occupation: 'Doctor',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Yoga', 'Meditation', 'Traveling'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 7,
    name: 'Pooja More',
    image: user3,
    about:
      'Easy-going and family-oriented person who enjoys dancing, photography, gardening, and traveling.',
    age: 25,
    location: 'Satara, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'BEd',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Dancing', 'Photography', 'Gardening'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 8,
    name: 'Sana Memon',
    image: user1,
    about:
      'Kind-hearted professional who enjoys cooking, baking, reading, and spending time with family.',
    age: 29,
    location: 'Mumbai, Maharashtra',
    religion: 'Muslim',
    community: 'Memon',
    education: 'BCom',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Baking', 'Reading'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 9,
    name: 'Riya Shah',
    image: user2,
    about:
      'Creative and cheerful person who enjoys music, painting, photography, and exploring new places.',
    age: 26,
    location: 'Thane, Maharashtra',
    religion: 'Hindu',
    community: 'Bania',
    education: 'BBA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Music', 'Painting', 'Photography'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 10,
    name: 'Anjali Deshpande',
    image: user4,
    about:
      'MBA graduate who enjoys traveling, writing, reading, and spending weekends with friends.',
    age: 31,
    location: 'Pune, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'MBA',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Occasionally',
    hobbies: ['Traveling', 'Writing', 'Reading'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 11,
    name: 'Maria Fernandes',
    image: user5,
    about:
      'Friendly teacher who loves reading, cooking, gardening, and spending peaceful time near nature.',
    age: 28,
    location: 'Vasai-Virar, Maharashtra',
    religion: 'Christian',
    community: 'Catholic',
    education: 'MA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Reading', 'Cooking', 'Gardening'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 12,
    name: 'Shreya Shah',
    image: user6,
    about:
      'Simple and ambitious professional who enjoys dancing, music, photography, and traveling.',
    age: 27,
    location: 'Mumbai, Maharashtra',
    religion: 'Jain',
    community: 'Shwetambar',
    education: 'BCom',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Dancing', 'Music', 'Photography'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 13,
    name: 'Simran Kaur',
    image: user1,
    about:
      'Cheerful and caring person who enjoys dancing, yoga, traveling, and spending time with family.',
    age: 29,
    location: 'Navi Mumbai, Maharashtra',
    religion: 'Sikh',
    community: 'Khatri',
    education: 'BBA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Dancing', 'Yoga', 'Traveling'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 14,
    name: 'Divya Reddy',
    image: user3,
    about:
      'Doctor who enjoys meditation, reading, yoga, and spending peaceful weekends with family.',
    age: 33,
    location: 'Nagpur, Maharashtra',
    religion: 'Hindu',
    community: 'Reddy',
    education: 'MD',
    height: `5'0" - 5'5"`,
    occupation: 'Doctor',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Meditation', 'Reading', 'Yoga'],
    annualIncome: '₹30 - ₹50 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 15,
    name: 'Isha Verma',
    image: user2,
    about:
      'Creative professional who enjoys writing, photography, painting, and exploring art.',
    age: 25,
    location: 'Nashik, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'BA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Writing', 'Photography', 'Painting'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 16,
    name: 'Fatima Khan',
    image: user4,
    about:
      'Family-oriented person who enjoys cooking, gardening, reading, and volunteering.',
    age: 32,
    location: 'Mumbai, Maharashtra',
    religion: 'Muslim',
    community: 'Sunni Barelvi',
    education: 'MA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Gardening', 'Reading'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 17,
    name: 'Radhika Joshi',
    image: user5,
    about:
      'Teacher who enjoys classical music, reading, meditation, and spending time with family.',
    age: 39,
    location: 'Amravati, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'MA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Widowed',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Music', 'Reading', 'Meditation'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 18,
    name: 'Tanvi Kulkarni',
    image: user6,
    about:
      'MBA professional who enjoys traveling, baking, photography, and spending time with friends.',
    age: 30,
    location: 'Pune, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'MBA',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Occasionally',
    hobbies: ['Traveling', 'Baking', 'Photography'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 19,
    name: 'Nandini Rao',
    image: user3,
    about:
      'Software professional who enjoys reading, yoga, learning languages, and traveling.',
    age: 27,
    location: 'Mumbai, Maharashtra',
    religion: 'Hindu',
    community: 'Lingayat',
    education: 'MTech',
    height: `5'0" - 5'5"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Reading', 'Yoga', 'Learning Languages'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 20,
    name: 'Madhuri Agrawal',
    image: user1,
    about:
      'Finance professional who enjoys cooking, music, volunteering, and community activities.',
    age: 33,
    location: 'Akola, Maharashtra',
    religion: 'Hindu',
    community: 'Vaishya',
    education: 'MCom',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Music', 'Volunteering'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 21,
    name: 'Harshita Jain',
    image: user4,
    about:
      'Kind and ambitious professional who enjoys painting, baking, reading, and creative activities.',
    age: 26,
    location: 'Pune, Maharashtra',
    religion: 'Jain',
    community: 'Digambar',
    education: 'BCom',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Painting', 'Baking', 'Reading'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 22,
    name: 'Jasleen Kaur',
    image: user2,
    about:
      'Creative and cheerful person who enjoys singing, dancing, photography, and traveling.',
    age: 28,
    location: 'Thane, Maharashtra',
    religion: 'Sikh',
    community: 'Arora',
    education: 'BBA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Singing', 'Dancing', 'Photography'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 23,
    name: 'Aarti Shinde',
    image: user5,
    about:
      'Warm and positive person who enjoys cooking, music, home decoration, and family time.',
    age: 37,
    location: 'Latur, Maharashtra',
    religion: 'Hindu',
    community: 'Dhangar',
    education: 'BEd',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Separated',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Music', 'Home Decoration'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 24,
    name: 'Elizabeth Thomas',
    image: user6,
    about:
      'Caring and independent professional who enjoys singing, reading, volunteering, and helping others.',
    age: 31,
    location: 'Vasai-Virar, Maharashtra',
    religion: 'Christian',
    community: 'Syrian Christian',
    education: 'MSc',
    height: `5'0" - 5'5"`,
    occupation: 'Doctor',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Singing', 'Reading', 'Volunteering'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 25,
    name: 'Ananya Patil',
    image: user3,
    about:
      'Family-oriented and optimistic person who enjoys dancing, photography, hiking, and exploring nature.',
    age: 30,
    location: 'Kolhapur, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'MCA',
    height: `5'0" - 5'5"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Dancing', 'Photography', 'Hiking'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 26,
    name: 'Pallavi Bhosale',
    image: user1,
    about:
      'Software engineer who enjoys cycling, hiking, gaming, and exploring new places.',
    age: 29,
    location: 'Nagpur, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'BE',
    height: `5'6" - 6'0"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Cycling', 'Hiking', 'Gaming'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 27,
    name: 'Komal Pawar',
    image: user4,
    about:
      'Friendly professional who enjoys cooking, gardening, music, and weekend trips.',
    age: 32,
    location: 'Satara, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'MBA',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Occasionally',
    hobbies: ['Cooking', 'Gardening', 'Music'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 28,
    name: 'Sonal Patil',
    image: user5,
    about:
      'Doctor who loves reading, yoga, meditation, and maintaining a healthy lifestyle.',
    age: 35,
    location: 'Nashik, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'MBBS',
    height: `5'0" - 5'5"`,
    occupation: 'Doctor',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Reading', 'Yoga', 'Meditation'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 29,
    name: 'Rupali More',
    image: user6,
    about:
      'Teacher who enjoys dancing, painting, cooking, and spending time with family.',
    age: 24,
    location: 'Solapur, Maharashtra',
    religion: 'Hindu',
    community: 'Mali',
    education: 'BEd',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Dancing', 'Painting', 'Cooking'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 30,
    name: 'Farheen Shaikh',
    image: user2,
    about:
      'Ambitious professional who enjoys traveling, photography, cooking, and learning new skills.',
    age: 30,
    location: 'Aurangabad, Maharashtra',
    religion: 'Muslim',
    community: 'Sunni',
    education: 'MBA',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Traveling', 'Photography', 'Cooking'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 31,
    name: 'Sakshi Kulkarni',
    image: user3,
    about:
      'Software professional who enjoys reading, music, gaming, and weekend travel.',
    age: 28,
    location: 'Pune, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'MCA',
    height: `5'0" - 5'5"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Occasionally',
    hobbies: ['Reading', 'Music', 'Gaming'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 32,
    name: 'Vaishnavi Desai',
    image: user1,
    about:
      'Creative professional who enjoys singing, playing piano, painting, and traveling.',
    age: 26,
    location: 'Mumbai, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'BFA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Singing', 'Playing Piano', 'Painting'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 33,
    name: 'Mitali Joshi',
    image: user4,
    about:
      'Finance professional who enjoys reading, chess, board games, and traveling.',
    age: 36,
    location: 'Thane, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'MCom',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Divorced',
    familyType: 'Nuclear Family',
    drinking: 'Occasionally',
    hobbies: ['Reading', 'Chess', 'Board Games'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 34,
    name: 'Nisha Yadav',
    image: user5,
    about:
      'Energetic professional who enjoys cricket, fitness, cycling, and outdoor activities.',
    age: 31,
    location: 'Jalgaon, Maharashtra',
    religion: 'Hindu',
    community: 'Yadav',
    education: 'BCom',
    height: `5'6" - 6'0"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Occasionally',
    hobbies: ['Cricket', 'Fitness', 'Cycling'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 35,
    name: 'Roshni Reddy',
    image: user6,
    about:
      'Doctor who enjoys meditation, yoga, reading, and exploring different cultures.',
    age: 34,
    location: 'Nagpur, Maharashtra',
    religion: 'Hindu',
    community: 'Reddy',
    education: 'MD',
    height: `5'0" - 5'5"`,
    occupation: 'Doctor',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Meditation', 'Yoga', 'Reading'],
    annualIncome: '₹30 - ₹50 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 36,
    name: 'Monika Jain',
    image: user2,
    about:
      'Calm and family-oriented person who enjoys baking, painting, reading, and meditation.',
    age: 29,
    location: 'Pune, Maharashtra',
    religion: 'Jain',
    community: 'Digambar',
    education: 'MBA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Baking', 'Painting', 'Meditation'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 37,
    name: 'Harleen Kaur',
    image: user3,
    about:
      'Technology professional who enjoys cycling, gaming, music, and playing guitar.',
    age: 30,
    location: 'Navi Mumbai, Maharashtra',
    religion: 'Sikh',
    community: 'Khatri',
    education: 'BTech',
    height: `5'6" - 6'0"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Occasionally',
    hobbies: ['Cycling', 'Gaming', 'Playing Guitar'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 38,
    name: 'Poonam Bhandari',
    image: user1,
    about:
      'Mature and caring professional who enjoys gardening, reading, meditation, and cooking.',
    age: 40,
    location: 'Chandrapur, Maharashtra',
    religion: 'Hindu',
    community: 'Bhandari',
    education: 'MCom',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Widowed',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Gardening', 'Reading', 'Meditation'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 39,
    name: 'Ritu Agrawal',
    image: user4,
    about:
      'Finance professional who enjoys cooking, volunteering, music, and traveling.',
    age: 35,
    location: 'Akola, Maharashtra',
    religion: 'Hindu',
    community: 'Vaishya',
    education: 'MCom',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Volunteering', 'Music'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 40,
    name: 'Shalini Nair',
    image: user5,
    about:
      'Doctor who enjoys swimming, yoga, traveling, and spending time outdoors.',
    age: 32,
    location: 'Mumbai, Maharashtra',
    religion: 'Hindu',
    community: 'Nair',
    education: 'MBBS',
    height: `5'0" - 5'5"`,
    occupation: 'Doctor',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Swimming', 'Yoga', 'Traveling'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 41,
    name: 'Kiran Patil',
    image: user6,
    about:
      'Simple and optimistic professional who enjoys farming, gardening, cooking, and family time.',
    age: 38,
    location: 'Sangli, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'BBA',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Gardening', 'Cooking', 'Reading'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 42,
    name: 'Aparna Deshmukh',
    image: user2,
    about:
      'Teacher who enjoys writing, reading, photography, and volunteering in community activities.',
    age: 36,
    location: 'Amravati, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'MA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Writing', 'Reading', 'Volunteering'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 43,
    name: 'Saira Khan',
    image: user3,
    about:
      'Business professional who enjoys traveling, cooking, photography, and exploring new places.',
    age: 33,
    location: 'Bhiwandi, Maharashtra',
    religion: 'Muslim',
    community: 'Khoja',
    education: 'BBA',
    height: `5'0" - 5'5"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Traveling', 'Cooking', 'Photography'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 44,
    name: 'Grace Dsouza',
    image: user1,
    about:
      'Independent and caring professional who enjoys singing, music, volunteering, and traveling.',
    age: 29,
    location: 'Vasai-Virar, Maharashtra',
    religion: 'Christian',
    community: 'Catholic',
    education: 'MSc',
    height: `5'0" - 5'5"`,
    occupation: 'Doctor',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Singing', 'Music', 'Volunteering'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 45,
    name: 'Rupal Shah',
    image: user4,
    about:
      'Entrepreneur who enjoys traveling, collecting, photography, and board games.',
    age: 41,
    location: 'Mumbai, Maharashtra',
    religion: 'Jain',
    community: 'Shwetambar',
    education: 'MBA',
    height: `5'6" - 6'0"`,
    occupation: 'Business Owner',
    maritalStatus: 'Never Married',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Traveling', 'Board Games', 'Collecting'],
    annualIncome: 'Above ₹50 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 46,
    name: 'Bhagyashree Pawar',
    image: user5,
    about:
      'Cheerful professional who enjoys dancing, fitness, hiking, and outdoor adventures.',
    age: 28,
    location: 'Kalyan-Dombivli, Maharashtra',
    religion: 'Hindu',
    community: 'Maratha',
    education: 'BTech',
    height: `5'0" - 5'5"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Occasionally',
    hobbies: ['Dancing', 'Fitness', 'Hiking'],
    annualIncome: '₹10 - ₹20 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 47,
    name: 'Mansi Kulkarni',
    image: user6,
    about:
      'Software professional who enjoys reading, gaming, music, and learning new technologies.',
    age: 27,
    location: 'Pune, Maharashtra',
    religion: 'Hindu',
    community: 'Brahmin',
    education: 'MTech',
    height: `5'0" - 5'5"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Reading', 'Gaming', 'Music'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Moderate',
    smoking: 'Never',
  },

  {
    id: 48,
    name: 'Rachana More',
    image: user2,
    about:
      'Family-oriented person who enjoys cooking, gardening, painting, and spending time with loved ones.',
    age: 43,
    location: 'Solapur, Maharashtra',
    religion: 'Hindu',
    community: 'Mali',
    education: 'BA',
    height: `5'0" - 5'5"`,
    occupation: 'Teacher',
    maritalStatus: 'Divorced',
    familyType: 'Joint Family',
    drinking: 'Never',
    hobbies: ['Cooking', 'Gardening', 'Painting'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Traditional',
    smoking: 'Never',
  },

  {
    id: 49,
    name: 'Nikita Reddy',
    image: user3,
    about:
      'Ambitious software professional who enjoys traveling, fitness, photography, and learning languages.',
    age: 31,
    location: 'Nagpur, Maharashtra',
    religion: 'Hindu',
    community: 'Reddy',
    education: 'BTech',
    height: `5'6" - 6'0"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Occasionally',
    hobbies: ['Traveling', 'Fitness', 'Learning Languages'],
    annualIncome: '₹20 - ₹30 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },

  {
    id: 50,
    name: 'Ishita Mehta',
    image: user1,
    about:
      'Technology enthusiast who enjoys reading, chess, gaming, traveling, and exploring new places.',
    age: 24,
    location: 'Mumbai, Maharashtra',
    religion: 'Hindu',
    community: 'Bania',
    education: 'BCA',
    height: `5'0" - 5'5"`,
    occupation: 'Software Engineer',
    maritalStatus: 'Never Married',
    familyType: 'Nuclear Family',
    drinking: 'Never',
    hobbies: ['Reading', 'Chess', 'Gaming'],
    annualIncome: '₹5 - ₹10 Lakh',
    lifestyle: 'Liberal',
    smoking: 'Never',
  },
];
