import {
  LayoutDashboard,
  Heart,
  Search,
  MessageCircle,
  UserPlus,
  Eye,
  Settings,
  Star,
  Calendar,
  User,
  Crown,
  CircleQuestionMark,
} from 'lucide-react';
import type { SidebarMenu } from './types';

export const sidebarMenu: SidebarMenu[] = [
  {
    id: 1,
    label: 'Dashboard',
    icon: LayoutDashboard,
    path: '/dashboard',
  },
  {
    id: 2,
    label: 'Matches',
    icon: Heart,
    path: '/matches',
    badge: 12,
  },
  {
    id: 3,
    label: 'Search',
    icon: Search,
    path: '/search',
  },
  {
    id: 4,
    label: 'Messages',
    icon: MessageCircle,
    path: '/messages',
    badge: 5,
  },
  {
    id: 5,
    label: 'Interests',
    icon: UserPlus,
    path: '/interests',
    badge: 4,
  },
  {
    id: 6,
    label: 'Who Viewed Me',
    icon: Eye,
    path: '/views',
    badge: 8,
  },
  {
    id: 7,
    label: 'Shortlisted',
    icon: Star,
    path: '/shortlisted',
    badge: 7,
  },
  {
    id: 8,
    label: 'Events',
    icon: Calendar,
    path: '/events',
  },
  {
    id: 9,
    label: 'My Profile',
    icon: User,
    path: '/profile',
  },
  {
    id: 10,
    label: 'Premium',
    icon: Crown,
    path: '/premium',
  },
  {
    id: 11,
    label: 'Settings',
    icon: Settings,
    path: '/settings',
  },
  {
    id: 12,
    label: 'Help & Support',
    icon: CircleQuestionMark,
    path: '/help-and-support',
  },
];
